apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
 name: require-cpu-memory-requests
spec:
 validationFailureAction: Enforce
 background: true
 rules:
   - name: require-cpu-memory
     match:
       resources:
         kinds:
           - Pod
     validate:
       message: "CPU and memory requests and limits are required for all containers."
       foreach:
        - list: "spec.containers"
          deny: 
           conditions:
            - key: "{{ element.resources.requests.cpu }}"
              operator: Equals
              value: ""
            - key: "{{ element.resources.requests.cpu }}"
              operator: Equals
              value: ""
