apiVersion: v1
kind: Pod
metadata:
 name: limit-violating-pod
spec:
 containers:
   - name: app
     image: nginx
     resources:
       limits:
         cpu: "1000m"
         memory: "512Mi"
       requests:
         cpu: "500m"
         memory: "256Mi"