apiVersion: v1
kind: Pod
metadata:
 name: goodpod
 namespace: default
spec:
 containers:
   - name: nginx
     image: nginx
     resources:
       requests:
         memory: "128Mi"
         cpu: "100m"
       limits:
         memory: "128Mi"
         cpu: "500m"
     securityContext:
       privileged: false